apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab-mr-combiner.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "gitlab-mr-combiner.name" . }}
    chart: {{ include "gitlab-mr-combiner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gitlab-mr-combiner.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "gitlab-mr-combiner.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-config
          env:
          - name: GITLAB_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Chart.Name }}-secrets
                key: gitlabToken
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: ssh-keys
              mountPath: /root/.ssh/id_rsa
              subPath: sshKey
      volumes:
        - name: ssh-keys
          secret:
            secretName: {{ .Chart.Name }}-secrets
            defaultMode: 0600
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
