apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  gitlabToken: {{ .Values.secret.gitlabToken | b64enc | quote }}
  sshKey: {{ .Values.secret.sshKey | b64enc | quote }}
  secretToken: {{ .Values.secret.secretToken | b64enc | quote }}
